[workspace]
resolver = "2"

members = [
    "tfhesql-cli",
    "tfhesql",
]

[profile.dev.package."*"]
opt-level = 3
debug = false
split-debuginfo = '...'  # Platform-specific.
strip = "none"
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16
